name: Unity Build

on:
  push:
    branches:
      - main
      - actions/build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.0f1
          targetPlatform: StandaloneWindows64

      - name: Build project
        run: ./build.sh
